# Nothing important here, just a playground for testing functions

In [3]:
import pandas as pd
import numpy as np

In [4]:
A_SEQUENCES = np.array([['B','B','B'],
                        ['B','B','R'],
                        ['B','R','B'],
                        ['B','R','R'],
                        ['R','B','B'],
                        ['R','B','R'],
                        ['R','R','B'],
                            ['R','R','R']])
B_SEQUENCES = A_SEQUENCES.copy()

In [8]:
a_only = pd.DataFrame(data = np.zeros(shape=(8,4)),index = A_SEQUENCES, columns = ['Wins by Tricks','Ties by Tricks', 'Wins by Cards','Ties by Cards'])
a_only

           Wins by Tricks  Ties by Tricks  Wins by Cards  Ties by Cards
(B, B, B)             0.0             0.0            0.0            0.0
(B, B, R)             0.0             0.0            0.0            0.0
(B, R, B)             0.0             0.0            0.0            0.0
(B, R, R)             0.0             0.0            0.0            0.0
(R, B, B)             0.0             0.0            0.0            0.0
(R, B, R)             0.0             0.0            0.0            0.0
(R, R, B)             0.0             0.0            0.0            0.0
(R, R, R)             0.0             0.0            0.0            0.0

In [9]:
a = ['B','B','B']

In [10]:
a_only.at[tuple(a), 'Wins by Tricks'] += 3

In [17]:
match_sequences = []
for a in A_SEQUENCES:
        for b in B_SEQUENCES:
            if np.array_equal(a,b):
                continue
            match_sequences.append((tuple(a),tuple(b)))

df = pd.MultiIndex.from_tuples(match_sequences, names=['A','B'])
results = pd.DataFrame(0,index=df, columns=['Wins by Tricks','Wins by Cards','Ties by Tricks','Ties by Cards'])
results

                     Wins by Tricks  Wins by Cards  Ties by Tricks  \
A         B
(B, B, B) (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, B, R) (B, B, B)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, R)               0              0               0
(R, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0

                     Ties by Cards
A         B
(B, B, B) (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, B, R) (B, B, B)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, R, B)              0
          (R, R, R)              0
(R, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, R)              0
(R, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0

In [6]:
len(df)

56

In [7]:
results = pd.DataFrame(0,index=df, columns=['Wins by Tricks','Wins by Cards','Ties by Tricks','Ties by Cards'])
results

                     Wins by Tricks  Wins by Cards  Ties by Tricks  \
A         B
(B, B, B) (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, B, R) (B, B, B)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, R)               0              0               0
(R, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0

                     Ties by Cards
A         B
(B, B, B) (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, B, R) (B, B, B)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, R, B)              0
          (R, R, R)              0
(R, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, R)              0
(R, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0

In [18]:
idx_a = tuple(['B','B','R'])
idx_b = tuple(['B','B','B'])
results.at[(idx_a,idx_b), 'Wins by Tricks'] +=1

In [19]:
results

                     Wins by Tricks  Wins by Cards  Ties by Tricks  \
A         B
(B, B, B) (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, B, R) (B, B, B)               1              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(B, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, B, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, R, B)               0              0               0
          (R, R, R)               0              0               0
(R, R, B) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, R)               0              0               0
(R, R, R) (B, B, B)               0              0               0
          (B, B, R)               0              0               0
          (B, R, B)               0              0               0
          (B, R, R)               0              0               0
          (R, B, B)               0              0               0
          (R, B, R)               0              0               0
          (R, R, B)               0              0               0

                     Ties by Cards
A         B
(B, B, B) (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, B, R) (B, B, B)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(B, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, R)              0
          (R, R, B)              0
          (R, R, R)              0
(R, B, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, R, B)              0
          (R, R, R)              0
(R, R, B) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, R)              0
(R, R, R) (B, B, B)              0
          (B, B, R)              0
          (B, R, B)              0
          (B, R, R)              0
          (R, B, B)              0
          (R, B, R)              0
          (R, R, B)              0